<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="AhmadMalloh" name="Parallel Tests" tests="2" failures="0" timestamp="11 Dec 2021 18:29:02 GMT" time="0.038" errors="0">
  <testcase name="@AfterMethod afterMethod" time="0.0" classname="SanityTest.Contact_US">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at Configration.ConfigData.teardown(ConfigData.java:72)
	at SanityTest.Contact_US.afterMethod(Contact_US.java:30)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod afterMethod -->
  <testcase name="@BeforeMethod beforeMethod" time="0.0" classname="SanityTest.Contact_US">
    <skipped/>
  </testcase> <!-- @BeforeMethod beforeMethod -->
  <testcase name="@AfterMethod afterMethod" time="0.0" classname="SanityTest.Contact_US">
    <skipped/>
  </testcase> <!-- @AfterMethod afterMethod -->
  <testcase name="Send_Message" time="0.009" classname="SanityTest.Contact_US">
    <skipped/>
  </testcase> <!-- Send_Message -->
  <testcase name="Send_Message" time="0.0" classname="SanityTest.Contact_US">
    <skipped/>
  </testcase> <!-- Send_Message -->
</testsuite> <!-- Parallel Tests -->
